/*
 * genBlockList 模块的一部分：不依赖 Minecraft / NeoForge。
 */
package yee.pltision.brfurniture.genblocklist;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * 把方块 id 与基础名写成一个纯 Java 常量类，交给主模块编译。
 *
 * <p>刻意不做"读资源文件"的方案：服务端不加载贴图，而且贴图/资源可以在打包后随意替换，
 * 只有硬编码的默认列表才能在配置缺失时给出稳定、可复现的默认值。</p>
 */
public final class DefaultBlockIdsWriter {
    private static final String FILE_NAME = "DefaultBlockIds.java";
    /** 生成结果里，头部注释之后真正是代码的那一段的起始标记。 */
    private static final String BODY_START = "package ";

    private final String packageName;
    private final String simpleClassName;

    public DefaultBlockIdsWriter(String packageName, String simpleClassName) {
        this.packageName = packageName;
        this.simpleClassName = simpleClassName;
    }

    /**
     * 写出 {@code <outputDir>/<packagePath>/DefaultBlockIds.java}。
     *
     * <p>如果只有时间戳变了、内容没变，就<b>不动</b>原文件：否则每次构建都会刷新文件时间，
     * 让增量编译失效。</p>
     *
     * @return 生成的文件路径
     */
    public Path write(Path outputDir, List<String> ids, List<BlockNameResolver.LocalizedName> names, String sourceDescription)
            throws IOException {
        if (ids.size() != names.size()) {
            throw new IllegalArgumentException("ids(" + ids.size() + ") 与 names(" + names.size() + ") 数量不一致");
        }

        Path packageDir = outputDir.resolve(packageName.replace('.', '/'));
        Files.createDirectories(packageDir);
        Path file = packageDir.resolve(FILE_NAME);

        String body = buildBody(ids, names);
        if (Files.isRegularFile(file)) {
            String existing = Files.readString(file, StandardCharsets.UTF_8);
            int bodyStart = existing.indexOf(BODY_START);
            if (bodyStart >= 0 && existing.substring(bodyStart).equals(body)) {
                System.out.println("[genBlockList] " + file + " 已经是最新的，不重写");
                return file;
            }
        }

        Files.writeString(file, buildHeader(sourceDescription) + body, StandardCharsets.UTF_8);
        System.out.println("[genBlockList] 已写出 " + file + "（" + ids.size() + " 个方块 id）");
        return file;
    }

    private String buildHeader(String sourceDescription) {
        return """
                /*
                 * Generated by the genBlockList module. Do not edit by hand.
                 *
                 * Source: %s
                 * Run `gradlew :genBlockList:generateDefaultBlockIds` (or simply build) to refresh.
                 */
                """.formatted(sourceDescription);
    }

    private String buildBody(List<String> ids, List<BlockNameResolver.LocalizedName> names) {
        StringBuilder body = new StringBuilder();
        body.append("package ").append(packageName).append(";\n\n");
        body.append("""
                import java.util.List;
                import java.util.Map;

                /**
                 * Hard coded default block ids, used when {@code config/brfurniture/blocks.txt} is absent
                 * and as the input of the datagen providers.
                 *
                 * <p>Generated %s from %d block texture(s).</p>
                 */
                """.formatted(Instant.now(), ids.size()));
        body.append("public final class ").append(simpleClassName).append(" {\n");

        body.append("    /** Block ids, relative to the {@code brfurniture} namespace, in a stable order. */\n");
        body.append("    public static final List<String> IDS = List.of(\n");
        body.append(joinEntries(ids, 12, id -> "            \"" + escape(id) + "\""));
        body.append("    );\n\n");

        appendNameMap(body, "BASE_NAMES_ZH_CN", "Simplified Chinese base name of every id in {@link #IDS}, without variety suffixes.",
                ids, names, name -> name.zhCn());
        appendNameMap(body, "BASE_NAMES_EN_US", "English base name of every id in {@link #IDS}, without variety suffixes.",
                ids, names, name -> name.enUs());

        body.append("    private ").append(simpleClassName).append("() {}\n");
        body.append("}\n");
        return body.toString();
    }

    private void appendNameMap(StringBuilder body, String fieldName, String javadoc, List<String> ids,
            List<BlockNameResolver.LocalizedName> names, java.util.function.Function<BlockNameResolver.LocalizedName, String> pick) {
        body.append("    /** ").append(javadoc).append(" */\n");
        body.append("    public static final Map<String, String> ").append(fieldName).append(" = Map.ofEntries(\n");
        List<String> entries = new ArrayList<>(ids.size());
        for (int i = 0; i < ids.size(); i++) {
            entries.add("            Map.entry(\"" + escape(ids.get(i)) + "\", \"" + escape(pick.apply(names.get(i))) + "\")");
        }
        body.append(String.join(",\n", entries)).append(");\n\n");
    }

    /** 每行 {@code perLine} 个元素，行尾逗号让 diff 更稳定。 */
    private static String joinEntries(List<String> values, int perLine, java.util.function.Function<String, String> format) {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < values.size(); i++) {
            builder.append(format.apply(values.get(i)));
            builder.append(i == values.size() - 1 ? "\n" : ",\n");
        }
        return builder.toString();
    }

    private static String escape(String value) {
        StringBuilder builder = new StringBuilder(value.length() + 8);
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            switch (c) {
                case '\\' -> builder.append("\\\\");
                case '"' -> builder.append("\\\"");
                case '\n' -> builder.append("\\n");
                case '\r' -> builder.append("\\r");
                case '\t' -> builder.append("\\t");
                default -> builder.append(c);
            }
        }
        return builder.toString();
    }
}
